### ISSUE TITLE
BUG: Missing seaborn

### ISSUE THREAD

**Issue by jakirkham** [binder-project/example-requirements#1]
Tried clicking the badge, but found the example was missing `seaborn`. Looking at the `Dockerfile`, it appears not to run `pip` with our requirements.

**Comment by freeman-lab** [comment]
@jakirkham thanks for noting this! This repo is intended to be built with the `requirements.txt` file, which get appended with a `pip` install to the `Dockerfile` at build time. 

The reason you saw `seaborn` missing is most likely that someone built a Binder for this repo **without** specifying the `requirements.txt` file. Currently, anyone can build a binder for anyone's repo, so this does happen occasionally on our examples.

But I just rebuilt it now and seaborn is there.

**Comment by lballabio** [comment]
You might want to rebuild it again :)

**Comment by kubu4** [comment]
Getting an ImportError for seaborn...

**Comment by jarthurgross** [comment]
I'm also having problems when running it on mybinder by clicking on the badge. When I try to run the first cell with code, I get:

``` python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-4b9dcb53f716> in <module>()
      1 get_ipython().magic(u'matplotlib inline')
      2 import matplotlib.pyplot as plt
----> 3 import seaborn as sns

ImportError: No module named seaborn
```

I'm surprised this isn't getting more attention, given that it's linked to from the front page of [mybinder.org](http://www.mybinder.org).
